networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  adminer:
    image: adminer:latest
    hostname: ${HOSTNAME:-adminer}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - ADMINER_PLUGINS=${ADMINER_PLUGINS:-}
      - ADMINER_DESIGN=${ADMINER_DESIGN:-adminer-dark}
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER:-}
    restart: unless-stopped
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"