networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  arkime:
    image: ${IMAGE:-ghcr.io/arkime/arkime/arkime:v5-latest}
    hostname: ${HOSTNAME:-arkime-viewer}
    domainname: ${DOMAINNAME:-localhost}
    # custom string of commands to support config.ini file if it is missing
    ### NOTE: You will probably need to use --insecure for most self-hosted Elasticsearch HTTPS interfaces, but don't use it if you don't need it, e.g. if you can access ES via a HTTPS URL with a commonly trusted public CA signed certificate or if you have setup private CA trust via another means.
    command: /bin/bash -l -c 'mkdir -p /opt/arkime/etc && touch /opt/arkime/etc/config.ini && /opt/arkime/bin/docker.sh viewer'
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      ### Refer to https://arkime.com/settings for complete reference.
      #- ARKIME__<config>=<value>
      #- ARKIME_<section>__<config>=<value>
      # Common to both capture and viewer
      - ARKIME__geoLite2ASN=${ARKIME__geoLite2ASN:-/usr/share/GeoIP/GeoLite2-ASN.mmdb;/opt/arkime/etc/GeoLite2-ASN.mmdb}
      - ARKIME__geoLite2Country=${ARKIME__geoLite2Country:-/usr/share/GeoIP/GeoLite2-Country.mmdb;/opt/arkime/etc/GeoLite2-Country.mmdb}
      - ARKIME__elasticsearch=${ARKIME__elasticsearch:-http://elastic:changeme@elasticsearch:9200}

      # Viewer - https://arkime.com/settings#viewer
      - ARKIME__viewPort=${ARKIME__viewPort:-80}
      - ARKIME__authMode=${ARKIME__authMode:-digest}
      - ARKIME__uploadCommand=${ARKIME__uploadCommand:-/opt/arkime/bin/capture --copy -n {NODE} -r {TMPFILE} -c {CONFIG} {TAGS}}
      - ARKIME__cronQueries=${ARKIME__cronQueries:-false}
      - ARKIME__dropUser=${ARKIME__dropUser:-www-data}
      - ARKIME__dropGroup=${ARKIME__dropGroup:-www-data}
    networks:
      network:
    #volumes:
      #- etc:/opt/arkime/etc
      #- ${DATA_DIR:-/opt/data/portainer/config/arkime}/config.ini:/opt/arkime/etc/config.ini
      # /usr/share/GeoIP:/usr/share/GeoIP
    healthcheck:
      test: wget --quiet --spider http://localhost:${ARKIME__viewPort:-80}/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arkime.rule=Host(`${HOSTNAME:-arkime}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.arkime.loadbalancer.server.port=${ARKIME__viewPort:-80}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"

#volumes:
#  etc:
