networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  browserless-chromium:
    image: ghcr.io/browserless/chromium:latest
    hostname: ${HOSTNAME:-browserless-chromium}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - CONCURRENT=${CONCURRENT:-10}
      - TOKEN=${TOKEN:-CHANGE_ME}
      - TZ=${TZ:-Australia/Brisbane}
    restart: unless-stopped
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.browserless_chromium.rule=Host(`browserless-chromium.localhost`)"
      - "traefik.http.services.browserless_chromium.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"