networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  caddy:
    image: docker.io/caddy:alpine
    hostname: ${HOSTNAME:-caddy}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    networks:
      network:
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /opt/data/portainer/config/caddy:/etc/caddy
      - /opt/data/portainer/config/caddy/srv:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      # - CF_API_TOKEN=super-secret-cloudflare-tokenvalue
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  caddy_data:
  caddy_config: