networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  cloudflared-proxy-doh:
    image: cloudflare/cloudflared:latest
    hostname: ${HOSTNAME:-cloudflared-proxy-doh}
    domainname: ${DOMAINNAME:-localhost}
    command: proxy-dns
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - TUNNEL_DNS_ADDRESS=${TUNNEL_DNS_ADDRESS:-0.0.0.0}
      - TUNNEL_DNS_PORT=${TUNNEL_DNS_PORT:-53}
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    networks:
      network:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"