networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  cloudflared-tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    hostname: ${HOSTNAME:-cloudflared-tunnel}
    domainname: ${DOMAINNAME:-localhost}
    command: tunnel run
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:-CHANGE_ME}
    restart: unless-stopped
    networks:
      network:
    labels:
      - "wud.watch=true"