networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  watchtower:
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    environment:
      - TUNNEL_DNS_ADDRESS=${TUNNEL_DNS_ADDRESS:-0.0.0.0}
      - TUNNEL_DNS_PORT=${TUNNEL_DNS_PORT:-53}
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always
    networks:
      network:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"