networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  coredns:
    image: docker.io/coredns/coredns:latest
    hostname: ${HOSTNAME:-coredns}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - EXAMPLE_ENV_VAR=${EXAMPLE_ENV_VAR:-example-value}
    restart: unless-stopped
    networks:
      network:
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - /opt/data/portainer/config/coredns:/etc/coredns
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"