networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  searxng:
    image: ghcr.io/gchq/cyberchef:latest
    hostname: ${HOSTNAME:-cyberchef}
    domainname: ${DOMAINNAME:-localhost}
    restart: always
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=Host(`cyberchef.localhost`)"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"