networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  elastic-agent:
    image: ${IMAGE:-docker.elastic.co/elastic-agent/elastic-agent-complete-wolfi:8.18.0}
    hostname: ${HOSTNAME:-elastic-agent}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - FLEET_ENROLL=${FLEET_ENROLL:-1}
      - FLEET_URL=${FLEET_URL:-CHANGE_ME}
      - FLEET_ENROLLMENT_TOKEN=${FLEET_ENROLLMENT_TOKEN:-CHANGE_ME}
    restart: unless-stopped
    volumes:
      - /opt/data/elastic-agent:/data:Z
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /run/podman/podman.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - elastic_agent_state:/usr/share/elastic-agent/state
    networks:
      network:
    healthcheck:
      test: "elastic-agent status"
      timeout: 2s
      start_period: 360s
      retries: 180
      interval: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elastic_agent.rule=Host(`${HOSTNAME:-elastic-agent}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.elastic_agent.loadbalancer.server.port=80"
      - "wud.watch=false"

volumes:
  elastic_agent_state: