networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  elasticvue:
    image: docker.io/cars10/elasticvue:latest
    hostname: ${HOSTNAME:-elasticvue}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - ELASTICVUE_CLUSTERS=${ELASTICVUE_CLUSTERS:-[\{"name":"local","uri":"https://elasticsearch.localhost","username":"elastic","password":"changeme"\}]}
    restart: unless-stopped
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticvue.rule=Host(`${HOSTNAME:-elasticvue}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.elasticvue.loadbalancer.server.port=8080"
      - "wud.watch=true"