networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  excalidraw:
    image: docker.io/excalidraw/excalidraw:latest
    hostname: ${HOSTNAME:-excalidraw}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`${HOSTNAME:-excalidraw}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"