networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  gpustack:
    image: docker.io/gpustack/gpustack:latest-rocm
    hostname: ${HOSTNAME:-gpustack}
    domainname: ${DOMAINNAME:-localhost}
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ipc: host
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    volumes:
      - /opt/amdgpu:/opt/amdgpu:ro
      - gpustack_data:/var/lib/gpustack
    networks:
      network:
    environment:
      - TZ=${TZ:-Australia/Brisbane}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpustack.rule=Host(`gpustack.localhost`)"
      - "traefik.http.services.gpustack.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  gpustack_data: