networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  gpustack:
    image: docker.io/gpustack/gpustack:latest-rocm
    hostname: ${HOSTNAME:-gpustack}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ipc: host
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    volumes:
      - /opt/amdgpu:/opt/amdgpu:ro
      - gpustack_data:/var/lib/gpustack
    networks:
      network:
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      # - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-10.3.0}
      # - HCC_AMDGPU_TARGET=${HCC_AMDGPU_TARGET:-gfx1030}
    healthcheck:
      test: curl --silent --fail http://localhost:80/version || exit 1
      interval: 60s
      retries: 3
      start_period: 3s
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpustack.rule=Host(`${HOSTNAME:-gpustack}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.gpustack.loadbalancer.server.port=80"
      - "wud.watch=true"

volumes:
  gpustack_data: