networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    hostname: ${HOSTNAME:-homepage}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS:-homepage.localhost}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro:Z
      # - /run/podman/podman.sock:/var/run/docker.sock:ro:Z
      - /opt/data/portainer/config/homepage:/app/config:Z
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${HOSTNAME:-homepage}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "wud.watch=true"