networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  hoppscotch:
    image: docker.io/hoppscotch/hoppscotch:latest
    hostname: ${HOSTNAME:-hoppscotch}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    networks:
      network:
    # ports:
    #   - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://hoppscotch:CHANGE_ME@postgres:5432/hoppscotch}
      # (Optional) By default, the AIO container (when in subpath access mode) exposes the endpoint on port 80. Use this setting to specify a different port if needed.
      # - HOPP_AIO_ALTERNATE_PORT=${HOPP_AIO_ALTERNATE_PORT:-3000}
      # Auth Tokens Config
      - JWT_SECRET=${JWT_SECRET:-CHANGE_ME}
      - TOKEN_SALT_COMPLEXITY=${TOKEN_SALT_COMPLEXITY:-10}
      - MAGIC_LINK_TOKEN_VALIDITY=${MAGIC_LINK_TOKEN_VALIDITY:-3}
      # Default validity is 7 days (604800000 ms) in ms
      - REFRESH_TOKEN_VALIDITY=${REFRESH_TOKEN_VALIDITY:-604800000}
      # Default validity is 1 day (86400000 ms) in ms
      - ACCESS_TOKEN_VALIDITY=${ACCESS_TOKEN_VALIDITY:-86400000}
      - SESSION_SECRET=${SESSION_SECRET:-CHANGE_ME}
      # Recommended to be true, set to false if you are using http
      # Note: Some auth providers may not support http requests
      - ALLOW_SECURE_COOKIES=${ALLOW_SECURE_COOKIES:-false}
      # Sensitive Data Encryption Key while storing in Database (32 character)
      - DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY:-CHANGE_ME!CHANGE_ME!CHANGE_ME!@#}
      - REDIRECT_URL=${REDIRECT_URL:-http://hoppscotch.localhost}
      # Whitelisted origins for the Hoppscotch App.
      # This list controls which origins can interact with the app through cross-origin comms.
      # - localhost ports (3170, 3000, 3100): app, backend, development servers and services
      # - app://localhost_3200: Bundle server origin identifier
      #   NOTE: `3200` here refers to the bundle server (port 3200) that provides the bundles,
      #   NOT where the app runs. The app itself uses the `app://` protocol with dynamic
      #   bundle names like `app://{bundle-name}/`
      - WHITELISTED_ORIGINS=http://hoppscotch.localhost,app://hoppscotch.localhost,app://localhost_3200
      - VITE_ALLOWED_AUTH_PROVIDERS=${VITE_ALLOWED_AUTH_PROVIDERS:-EMAIL}
      # - GOOGLE_CLIENT_ID=************************************************
      # - GOOGLE_CLIENT_SECRET=************************************************
      # - GOOGLE_CALLBACK_URL=http://localhost:3170/v1/auth/google/callback
      # - GOOGLE_SCOPE=email,profile
      # - GITHUB_CLIENT_ID=************************************************
      # - GITHUB_CLIENT_SECRET=************************************************
      # - GITHUB_CALLBACK_URL=http://localhost:3170/v1/auth/github/callback
      # - GITHUB_SCOPE=user:email
      # - MICROSOFT_CLIENT_ID=************************************************
      # - MICROSOFT_CLIENT_SECRET=************************************************
      # - MICROSOFT_CALLBACK_URL=http://localhost:3170/v1/auth/microsoft/callback
      # - MICROSOFT_SCOPE=user.read
      # - MICROSOFT_TENANT=common
      - MAILER_SMTP_ENABLE=${MAILER_SMTP_ENABLE:-true}
      - MAILER_USE_CUSTOM_CONFIGS=${MAILER_USE_CUSTOM_CONFIGS:-true}
      - MAILER_ADDRESS_FROM=${MAILER_ADDRESS_FROM:-from@example.com}
      # - MAILER_SMTP_URL=${MAILER_SMTP_URL:-smtps://apikey:CHANGE_ME@smtp.sendgrid.net} # used if custom mailer configs is false
      - MAILER_SMTP_HOST=${MAILER_SMTP_HOST:-smtp.sendgrid.net}
      - MAILER_SMTP_PORT=${MAILER_SMTP_PORT:-465}
      - MAILER_SMTP_SECURE=${MAILER_SMTP_SECURE:-true}
      - MAILER_SMTP_USER=${MAILER_SMTP_USER:-apikey}
      - MAILER_SMTP_PASSWORD=${MAILER_SMTP_PASSWORD:-CHANGE_ME}
      - MAILER_TLS_REJECT_UNAUTHORIZED=${MAILER_TLS_REJECT_UNAUTHORIZED:-true}
      - RATE_LIMIT_TTL=${RATE_LIMIT_TTL:-60} # In seconds
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-256} # Max requests per IP
      - VITE_BASE_URL=${VITE_BASE_URL:-http://hoppscotch.localhost}
      - VITE_SHORTCODE_BASE_URL=${VITE_SHORTCODE_BASE_URL:-http://hoppscotch.localhost}
      - VITE_ADMIN_URL=${VITE_ADMIN_URL:-http://hoppscotch.localhost/admin}
      - VITE_BACKEND_GQL_URL=${VITE_BACKEND_GQL_URL:-http://hoppscotch.localhost/backend/graphql}
      - VITE_BACKEND_WS_URL=${VITE_BACKEND_WS_URL:-wss://hoppscotch.localhost/backend/graphql}
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL:-http://hoppscotch.localhost/backend/v1}
      - VITE_APP_TOS_LINK=${VITE_APP_TOS_LINK:-https://docs.hoppscotch.io/support/terms}
      - VITE_APP_PRIVACY_POLICY_LINK=${VITE_APP_PRIVACY_POLICY_LINK:-https://docs.hoppscotch.io/support/privacy}
      - ENABLE_SUBPATH_BASED_ACCESS=${ENABLE_SUBPATH_BASED_ACCESS:-true}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoppscotch.rule=Host(`${HOSTNAME:-hoppscotch}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.routers.hoppscotch.service=hoppscotch"
      - "traefik.http.services.hoppscotch.loadbalancer.server.port=80"