networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    hostname: ${HOSTNAME:-linkwarden}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/api/v1/logins || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - DATABASE_URL=${DATABASE_URL:-postgresql://linkwarden:CHANGE_ME@postgres:5432/linkwarden}
      - BASE_URL=${BASE_URL:-http://linkwarden.localhost}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://linkwarden.localhost/api/v1/auth}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-CHANGE_ME}
      - NEXT_PUBLIC_EMAIL_PROVIDER=${NEXT_PUBLIC_EMAIL_PROVIDER:-false}
      - EMAIL_FROM=${EMAIL_FROM:-do-not-reply@linkwarden.localhost}
      - EMAIL_SERVER=${EMAIL_SERVER:-smtp://apikey:CHANGE_ME@smtp.sendgrid.net:587}
      - NEXT_PUBLIC_DISABLE_REGISTRATION=${NEXT_PUBLIC_DISABLE_REGISTRATION:-false}
      - NEXT_PUBLIC_CREDENTIALS_ENABLED=${NEXT_PUBLIC_CREDENTIALS_ENABLED:-true}
      - DISABLE_NEW_SSO_USERS=${DISABLE_NEW_SSO_USERS:-true}
      - NEXT_PUBLIC_GOOGLE_ENABLED=${NEXT_PUBLIC_GOOGLE_ENABLED:-false}
      #- GOOGLE_CUSTOM_NAME=${GOOGLE_CUSTOM_NAME:-Google}
      #- GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-CHANGE_ME}
      #- GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-CHANGE_ME}
      - NEXT_PUBLIC_OLLAMA_ENDPOINT_URL=${NEXT_PUBLIC_OLLAMA_ENDPOINT_URL:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-phi3:mini-4k}
      - MEILI_HOST=${MEILI_HOST:-http://meilisearch:7700}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-CHANGE_ME-CHANGE_ME-CHANGE_ME-CHANGE_ME-CHANGE_ME}
      - DEBUG=${DEBUG:-false}
    # ports:
    #  - 3000:3000
    networks:
      network:
    volumes:
      # don't question the logic, it really is /data/data apparently...
      - linkwarden_data:/data/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.rule=Host(`${HOSTNAME:-linkwarden}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"

volumes:
  linkwarden_data: