networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  meilisearch:
    image: docker.io/getmeili/meilisearch:latest
    hostname: ${HOSTNAME:-meilisearch}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-CHANGE_ME-CHANGE_ME-CHANGE_ME-CHANGE_ME-CHANGE_ME}
    volumes:
      - meilisearch_data:/meili_data
    networks:
      network:
    #ports:
    #  - 7700:7700
    healthcheck:
      test: curl --silent --fail http://localhost:7700/health | grep '{"status":"available"}' || exit 1
      interval: 60s
      retries: 3
      start_period: 3s
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch.rule=Host(`${HOSTNAME:-meilisearch}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.meilisearch.loadbalancer.server.port=7700"
      - "wud.watch=true"

volumes:
  meilisearch_data: