networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  mongo-express:
    image: ${IMAGE:-docker.io/mongo-express:latest}
    hostname: ${HOSTNAME:-mongo-express}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      ### Controls access to Mongo Express webUI,
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD:-CHANGE_ME}

      ### Mongo Express webUI settings,
      - ME_CONFIG_OPTIONS_EDITORTHEME=${ME_CONFIG_OPTIONS_EDITORTHEME:-default}
      - ME_CONFIG_REQUEST_SIZE=${ME_CONFIG_REQUEST_SIZE:-100kb}
      - ME_CONFIG_SITE_BASEURL=${ME_CONFIG_SITE_BASEURL:-/}
      - ME_CONFIG_SITE_COOKIESECRET=${ME_CONFIG_SITE_COOKIESECRET:-CHANGE_ME}
      - ME_CONFIG_SITE_SESSIONSECRET=${ME_CONFIG_SITE_SESSIONSECRET:-CHANGE_ME}
      - ME_CONFIG_SITE_SSL_ENABLED=${ME_CONFIG_SITE_SSL_ENABLED:-false}
      - ME_CONFIG_SITE_SSL_CRT_PATH=${ME_CONFIG_SITE_SSL_CRT_PATH:-}
      - ME_CONFIG_SITE_SSL_KEY_PATH=${ME_CONFIG_SITE_SSL_KEY_PATH:-}

      ### Where Mongo Express connects to,
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER:-mongo}

      ### For full admin of all databases
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN:-true}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD:-CHANGE_ME}

      ### For limited admin of specific database only
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN:-false}
      #- ME_CONFIG_MONGODB_AUTH_DATABASE=${ME_CONFIG_MONGODB_AUTH_DATABASE:-CHANGE_ME}
      #- ME_CONFIG_MONGODB_AUTH_USERNAME=${ME_CONFIG_MONGODB_AUTH_USERNAME:-CHANGE_ME}
      #- ME_CONFIG_MONGODB_AUTH_PASSWORD=${ME_CONFIG_MONGODB_AUTH_PASSWORD:-CHANGE_ME}
    networks:
      network:
    #ports:
    #  - 8081:8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo_express.rule=Host(`${HOSTNAME:-mongo-express}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.mongo_express.loadbalancer.server.port=8081"
      - "wud.watch=true"
