networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    hostname: ${HOSTNAME:-ollama}
    domainname: ${DOMAINNAME:-localhost}
    volumes:
      - ollama_data:/root/.ollama
    networks:
      network:
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-}
    healthcheck:
      test: timeout 5 bash -c "</dev/tcp/localhost/11434"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`${HOSTNAME:-ollama}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"

volumes:
  ollama_data: