networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  opcs-api:
    image: 1password/connect-api:latest
    hostname: ${HOSTNAME:-opcs-api}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
    volumes:
      - "/opt/data/portainer/config/opcs/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "opcs-data:/home/opuser/.op/data"
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opcs_api.rule=Host(`${HOSTNAME:-opcs-api}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.opcs_api.loadbalancer.server.port=8080"
      - "wud.watch=true"

  opcs-sync:
    image: 1password/connect-sync:latest
    hostname: ${HOSTNAME:-opcs-sync}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
    volumes:
      - "/opt/data/portainer/config/opcs/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "opcs-data:/home/opuser/.op/data"
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opcs_sync.rule=Host(`${HOSTNAME:-opcs-sync}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.opcs_sync.loadbalancer.server.port=8080"
      - "wud.watch=true"

volumes:
  opcs-data: