services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080/tcp"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      ## Ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}

      ## Searxng
      - ENABLE_RAG_WEB_SEARCH=${ENABLE_RAG_WEB_SEARCH:-false}
      - RAG_WEB_SEARCH_ENGINE=${RAG_WEB_SEARCH_ENGINE:-searxng}
      - RAG_WEB_SEARCH_RESULT_COUNT=${RAG_WEB_SEARCH_RESULT_COUNT:-3}
      - RAG_WEB_SEARCH_CONCURRENT_REQUEST=${RAG_WEB_SEARCH_CONCURRENT_REQUEST:-10}
      - SEARXNG_QUERY_URL=${SEARXNG_QUERY_URL:-http://searxng:8080/search?q=<query>}

      ## Web
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=${OAUTH_MERGE_ACCOUNTS_BY_EMAIL:-false}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-secret}
      - USE_CUDA_DOCKER=${USE_CUDA_DOCKER:-false}

      ## Database
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:P@55w0rd@postgres:5432/postgres}

    restart: always
    volumes:
      - open_webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open_webui.rule=Host(`open-webui.localhost`)"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  open_webui: