networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  pgadmin:
    image: docker.io/dpage/pgadmin4:${PG_MAJOR:-latest}
    hostname: ${HOSTNAME:-pgadmin}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-CHANGE@ME.tld}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-CHANGE_ME}
      - PGADMIN_DISABLE_POSTFIX=${PGADMIN_DISABLE_POSTFIX:-True}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=${PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION:-True}
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`${HOSTNAME:-pgadmin}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "wud.watch=true"

volumes:
  pgadmin: