networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  postgres:
    image: docker.io/postgres:${PG_MAJOR:-latest}
    hostname: ${HOSTNAME:-postgres}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-CHANGE_ME}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      network:
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=false"
      - "wud.watch=false"
      - "io.containers.autoupdate=local"

volumes:
  postgres: