networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  postgres:
    image: postgres:${PG_MAJOR:-latest}
    hostname: ${HOSTNAME:-postgres}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TIMEZONE:-Australia/Brisbane}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-CHANGE_ME}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_PASSWORD:-CHANGE_ME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      network:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres: