networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  postgres:
    image: postgres:${PG_MAJOR:-latest}
    hostname: ${HOSTNAME:-postgres}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TIMEZONE:-Australia/Brisbane}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-CHANGE_ME}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_PASSWORD:-CHANGE_ME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      network:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  pgadmin:
    image: dpage/pgadmin4:${PG_MAJOR:-latest}
    hostname: ${HOSTNAME:-pgadmin}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-CHANGE@ME.tld}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-CHANGE_ME}
      - PGADMIN_DISABLE_POSTFIX=${PGADMIN_DISABLE_POSTFIX:-True}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=${PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION:-True}
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres:
  pgadmin: