networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  rabbitmq:
    image: ${IMAGE:-docker.io/rabbitmq:4-management-alpine}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      # Refer to: https://www.rabbitmq.com/docs/configure#supported-environment-variables
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-CHANGE_ME}
    volumes:
#      - /opt/data/portainer/config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - amqpdata:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      network:
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=false"
      - "wud.watch=false"
      - "io.containers.autoupdate=local"

volumes:
  amqpdata: