networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  redis:
    image: ${IMAGE:-redis:7-alpine}
    hostname: ${HOSTNAME:-redis}
    domainname: ${DOMAINNAME:-localhost}
    restart: always
    environment:
      - TZ=${TZ:-Australia/Brisbane}
#    ports:
#      - "6379:6379"
    networks:
      network:
    volumes:
      - redisdata:/data
#      - /opt/data/portainer/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  redisdata: