networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  rsyslog:
    image: ${IMAGE:-docker.io/rsyslog/rsyslog-collector:latest}
    hostname: ${HOSTNAME:-rsyslog}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - $RSYSLOG_HOSTNAME=${$RSYSLOG_HOSTNAME:-rsyslog}
      - $RSYSLOG_ROLE=${$RSYSLOG_ROLE:-collector}
      #- $RSYSLOG_ROLE=${$RSYSLOG_ROLE:-docker}
      #- $$REMOTE_SERVER_NAME=${$REMOTE_SERVER_NAME:-syslog.elsehwere}
      #- $REMOTE_SERVER_PORT=${$REMOTE_SERVER_PORT:-514}
      #- $PERMIT_UNCLEAN_START=${$PERMIT_UNCLEAN_START:-}
    ports:
      - "514:514/udp"
      - "514:514/tcp"
      # "6514:6514/tcp"
    networks:
      network:
    volumes:
      #- /opt/data/portainer/config/rsyslog/rsyslog.conf:/etc/rsyslog.conf:ro
      #- /opt/data/portainer/config/rsyslog/rsyslog.d:/etc/rsyslog.d:ro
      - rsyslog_logs:/var/log
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"

volumes:
  rsyslog_logs: