networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    hostname: ${HOSTNAME:-searxng}
    domainname: ${DOMAINNAME:-localhost}
    volumes:
      - /opt/data/portainer/config/searxng:/etc/searxng
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - SEARXNG_HOSTNAME=${HOSTNAME:-searxng.localhost}
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-searxng.localhost}/
      - SEARXNG_URL=${SEARXNG_URL:-/}
      - SEARXNG_SECRET=${SEARXNG_SECRET:-CHANGE_ME}
      - SEARXNG_BIND_ADDRESS=${SEARXNG_BIND_ADDRESS:-[::]}
      - SEARXNG_PORT=${SEARXNG_PORT:-80}
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
      - BIND_ADDRESS=${SEARXNG_BIND_ADDRESS:-[::]}:${SEARXNG_PORT:-80}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped
    networks:
      network:
    healthcheck:
      test: ['CMD-SHELL', "wget --quiet --tries=1 --spider http://localhost:${SEARXNG_PORT:-80}/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`${HOSTNAME:-searxng}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.searxng.loadbalancer.server.port=80"
      - "wud.watch=true"