networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  searxng:
    image: searxng/searxng:latest
    hostname: ${HOSTNAME:-searxng}
    domainname: ${DOMAINNAME:-localhost}
    volumes:
      - /opt/data/portainer/config/searxng:/etc/searxng
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-secret}
      - SEARXNG_BIND_ADDRESS=${SEARXNG_BIND_ADDRESS:-0.0.0.0}
      - SEARXNG_PORT=${SEARXNG_PORT:-80}
      - SEARXNG_URL=${SEARXNG_URL:-/}
    restart: always
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.localhost`)"
      - "traefik.http.services.searxng.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"