networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  squid:
    image: docker.io/ubuntu/squid:latest
    hostname: ${HOSTNAME:-squid}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      - TZ=${TZ:-Australia/Brisbane}
    restart: unless-stopped
    volumes:
      - /opt/data/portainer/config/squid/squid.conf:/etc/squid/squid.conf:ro
      - squid_logs:/var/log/squid
      - squid_cache:/var/spool/squid
    networks:
      network:
#    ports:
#      - "3128:3128/tcp"
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.watch=true"
      - "io.containers.autoupdate=registry"

volumes:
  squid_cache:
  squid_logs: