networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    hostname: ${HOSTNAME:-uptime-kuma}
    domainname: ${DOMAINNAME:-localhost}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - UPTIME_KUMA_PORT=${UPTIME_KUMA_PORT:-80}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime_kuma:/app/data
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime_kuma.rule=Host(`uptime-kuma.localhost`)"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  uptime_kuma: