networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  uptime-kuma:
    #image: louislam/uptime-kuma:beta-slim
    image: ghcr.io/louislam/uptime-kuma:latest
    hostname: ${HOSTNAME:-uptime-kuma}
    domainname: ${DOMAINNAME:-localhost}
    environment:
      # Refer to: https://github.com/louislam/uptime-kuma/wiki/Environment-Variables
      - TZ=${TZ:-Australia/Brisbane}
      #- UPTIME_KUMA_HOST=${UPTIME_KUMA_HOST:-::}
      - UPTIME_KUMA_PORT=${UPTIME_KUMA_PORT:-8080}
      - UPTIME_KUMA_WS_ORIGIN_CHECK=${UPTIME_KUMA_WS_ORIGIN_CHECK:-cors-like}
      # Will only work for v2.x,
      #- UPTIME_KUMA_DB_TYPE=${UPTIME_KUMA_DB_TYPE:-mariadb}
      #- UPTIME_KUMA_DB_HOSTNAME=${UPTIME_KUMA_DB_HOSTNAME:-mariadb}
      #- UPTIME_KUMA_DB_PORT=${UPTIME_KUMA_DB_PORT:-3306}
      #- UPTIME_KUMA_DB_NAME=${UPTIME_KUMA_DB_NAME:-uptime_kuma}
      #- UPTIME_KUMA_DB_USERNAME=${UPTIME_KUMA_DB_USERNAME:-uptime_kuma}
      #- UPTIME_KUMA_DB_PASSWORD=${UPTIME_KUMA_DB_PASSWORD:-CHANGE_ME}
    restart: unless-stopped
    volumes:
      #- /run/podman/podman.sock:/var/run/docker.sock:Z
      #- /var/run/docker.sock:/var/run/docker.sock:Z
      - uptime_kuma:/app/data
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime_kuma.rule=Host(`${HOSTNAME:-uptime-kuma}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=${UPTIME_KUMA_PORT:-8080}"
      - "wud.watch=true"

volumes:
  uptime_kuma: