networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  web-check:
    image: lissy93/web-check:latest
    hostname: ${HOSTNAME:-web-check}
    domainname: ${DOMAINNAME:-localhost}
    restart: always
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_check.rule=Host(`web-check.localhost`)"
      - "traefik.http.services.web_check.loadbalancer.server.port=5377"
      - "com.centurylinklabs.watchtower.enable=true"