networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  web-check:
    image: docker.io/lissy93/web-check:latest
    hostname: ${HOSTNAME:-web-check}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Brisbane}
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_check.rule=Host(`${HOSTNAME:-web-check}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.web_check.loadbalancer.server.port=3000"
      - "wud.watch=true"