networks:
  network:
    name: ${NETWORK:-localnet}
    external: true

services:
  wud:
    image: docker.io/getwud/wud:latest
    hostname: ${HOSTNAME:-wud}
    domainname: ${DOMAINNAME:-localhost}
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - WUD_SERVER_PORT=${WUD_SERVER_PORT:-3000}
      - WUD_AUTH_BASIC_ADMIN_USER=${WUD_AUTH_BASIC_ADMIN_USER:-admin}
      - WUD_AUTH_BASIC_ADMIN_HASH=${WUD_AUTH_BASIC_ADMIN_HASH:-$$apr1$$RV0rTsSy$$eJR8jnlH1gzdXsVaKFrcO.}
      - WUD_WATCHER_LOCAL_CRON=${WUD_WATCHER_LOCAL_CRON:-0 10 * * *}
      - WUD_WATCHER_LOCAL_WATCHALL=${WUD_WATCHER_LOCAL_WATCHALL:-true}
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=${WUD_WATCHER_LOCAL_WATCHBYDEFAULT:-true}
      #- WUD_REGISTRY_HUB_PUBLIC_AUTH=CHANGE_ME
      #- WUD_TRIGGER_DOCKER_CONTAINERS_PRUNE=${WUD_TRIGGER_DOCKER_CONTAINERS_PRUNE:-true}
      #- WUD_TRIGGER_DOCKER_CONTAINERS_DRYRUN=${WUD_TRIGGER_DOCKER_CONTAINERS_DRYRUN:-true}
      #- WUD_TRIGGER_HTTP_WEBHOOK_URL=${WUD_TRIGGER_HTTP_WEBHOOK_URL:-https://your.domain/webhooks}
      #- WUD_TRIGGER_SMTP_SENDGRID_HOST=${WUD_TRIGGER_SMTP_SENDGRID_HOST:-smtp.sendgrid.net}
      #- WUD_TRIGGER_SMTP_SENDGRID_PORT=${WUD_TRIGGER_SMTP_SENDGRID_PORT:-587}
      #- WUD_TRIGGER_SMTP_SENDGRID_USER=${WUD_TRIGGER_SMTP_SENDGRID_USER:-apikey}
      #- WUD_TRIGGER_SMTP_SENDGRID_PASS=${WUD_TRIGGER_SMTP_SENDGRID_PASS:-CHANGE_ME}
      #- WUD_TRIGGER_SMTP_SENDGRID_FROM=${WUD_TRIGGER_SMTP_SENDGRID_FROM:-do-not-reply@your.domain}
      #- WUD_TRIGGER_SMTP_SENDGRID_TO=${WUD_TRIGGER_SMTP_SENDGRID_TO:-destination@your.domain}
      #- WUD_TRIGGER_SMTP_SENDGRID_TLS_ENABLED=${WUD_TRIGGER_SMTP_SENDGRID_TLS_ENABLED:-true}
      #- WUD_TRIGGER_SMTP_SENDGRID_TLS_VERIFY=${WUD_TRIGGER_SMTP_SENDGRID_TLS_VERIFY:-true}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      #- /run/podman/podman.sock:/var/run/docker.sock:Z
      - wud_state:/store
    #ports:
    #  - 3000:${WUD_SERVER_PORT:-3000}
    networks:
      network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`${HOSTNAME:-wud}.${DOMAINNAME:-localhost}`)"
      - "traefik.http.services.wud.loadbalancer.server.port=${WUD_SERVER_PORT:-3000}"
      - "wud.watch=false"
  
volumes:
  wud_state: